20240506 문제풀이
limbs722/ts-snippets pull request #10
Opened 2024-05-06 06:35 UTC by limbs722

@f-lab-jake 멘토님~ 코드리뷰 부탁드립니다~

2024-05-06 07:47 UTC, f-lab-jake requested changes

2024-05-06 07:47 UTC, f-lab-jake commented on level_0/간단한_식_계산하기.ts
> +            return Number(a) * Number(b);
중복을 제거하세요

2024-05-06 07:47 UTC, f-lab-jake commented on level_0/배열_만들기6.ts
> +            stk[stk.length - 1] === arr[i] ? stk.pop() : stk.push(arr[i]);
값을 쓰지않는 삼항연산자를 쓰지마세요. 즉 if문으로 바꾸란 얘깁니다.

2024-05-06 07:47 UTC, f-lab-jake commented on level_0/배열의 원소만큼 추가하기.ts
> +        }
`acc`를 수정하지마세요.

2024-05-06 07:47 UTC, f-lab-jake commented on level_0/빈_배열에_추가_삭제하기.ts
> +        }
`acc`를 수정하지마세요.

2024-05-06 07:47 UTC, f-lab-jake commented on level_0/배열의 원소만큼 추가하기.ts
> +        }
`acc` 수정을 못피하겠으면 차라리 `reduce`를 쓰지마세요

2024-05-07 09:23 UTC, limbs722 commented
@f-lab-jake  멘토님~ 피드백 주신 부분 반영해 보았습니다!

2024-05-09 02:00 UTC, f-lab-jake requested changes

2024-05-09 02:00 UTC, f-lab-jake commented on level_0/간단한_식_계산하기.ts
> +    };
창의적으로 잘했습니다.

2024-05-09 02:00 UTC, f-lab-jake commented on level_0/배열만들기6.ts
>      }
보니까 for ... of 문으로 되겠네요. 그리고 `Array.at`을 쓰세요.

2024-05-09 02:00 UTC, f-lab-jake commented on level_0/빈_배열에_추가_삭제하기.ts
> +    arr.forEach((value, idx) => {
lodash의 `zip`을 쓰세요.

2024-05-11 06:01 UTC, limbs722 commented
@f-lab-jake 멘토님 피드백 반영해보았습니다~!

2024-05-12 06:05 UTC, f-lab-jake requested changes

2024-05-12 06:05 UTC, f-lab-jake commented on level_0/배열만들기6.ts
>          }
중복을 제거해보세요.

2024-05-14 10:30 UTC, limbs722 commented
@f-lab-jake 중복 제거해서 수정했습니다~

2024-05-14 15:19 UTC, f-lab-jake approved these changes

2024-05-16 02:18 UTC, merged