20240511 문제풀이
limbs722/ts-snippets pull request #11
Opened 2024-05-11 06:02 UTC by limbs722

@f-lab-jake 멘토님~ 코드 리뷰 부탁드립니다~!

2024-05-12 06:09 UTC, f-lab-jake requested changes

2024-05-12 06:09 UTC, f-lab-jake commented on level_0/문자열_묶기.ts
> +        answer[str.length] = answer[str.length] + 1 || 1;
이게 사실
```js
answer[str.length] + 1 || (0 + 1);
```
을 의미하죠? 즉 `+ 1`이 중복되어있습니다. 그걸 제거하세요. 그리고 `||`말고 `??`가 필요할겁니다.

2024-05-12 06:09 UTC, f-lab-jake commented on level_0/배열비교하기.ts
> +    const arr2Sum = arr2.reduce((acc, value) => { return acc + value }, 0);
`reduce`의 사용을 피하세요. lodash의 `sum`을 쓰세요.

2024-05-12 06:09 UTC, f-lab-jake commented on level_0/배열의_길이를_2의_거듭제곱으로_만들기.ts
> +        }
else 빼세요.

2024-05-14 10:29 UTC, limbs722 commented
@f-lab-jake 피드백 주신 부분 반영해 보았습니다~ lodash sum 을 쓰니 훨씬 간결해지네요

2024-05-16 02:18 UTC, merged