20240512 문제풀이
limbs722/ts-snippets pull request #12
Opened 2024-05-12 04:48 UTC by limbs722

@f-lab-jake 멘토님~ 피드백 부탁드립니다~(__)

2024-05-12 06:13 UTC, f-lab-jake requested changes

2024-05-12 06:13 UTC, f-lab-jake commented on level_0/꼬리_문자열.ts
> +    }, '');
`reduce`쓰지말고 풀어보세요. 별개로, 이런 경우엔 대괄호 뺀 arrow function을 쓰에요.

2024-05-14 10:34 UTC, limbs722 commented
@f-lab-jake reduce 대신 filter 메소드를 사용해 다시 풀이 해보았습니다!

2024-05-14 15:19 UTC, f-lab-jake approved these changes

2024-05-16 02:18 UTC, merged