20240514 문제풀이
limbs722/ts-snippets pull request #13
Opened 2024-05-14 10:35 UTC by limbs722

@f-lab-jake 멘토님~ 피드백 부탁드립니다~

2024-05-14 15:23 UTC, f-lab-jake requested changes

2024-05-14 15:23 UTC, f-lab-jake commented on level_0/이차원_배열_대각선_순회하기.ts
> +    board.forEach((value, i) => {
`value`를 `row`로 재명명하세요

2024-05-14 15:23 UTC, f-lab-jake commented on level_0/이차원_배열_대각선_순회하기.ts
> +                result += board[i][j];
`board[i][j] = _`죠?

2024-05-14 15:23 UTC, f-lab-jake commented on level_0/정사각형으로_만들기.ts
> +            return v;
`v`를 변경하지마세요. `map`안에서 side effect를 발생시키는건 피하느게 좋습니다.

2024-05-14 15:23 UTC, f-lab-jake commented on level_0/정수를_나선형으로_배치하기.ts
> +    }
좀더 잘짜봅시다

2024-05-14 15:23 UTC, f-lab-jake commented on level_0/특별한_이차원_배열1.ts
> +            }
중복을 줄이세요

2024-05-24 01:40 UTC, limbs722 commented
@f-lab-jake  멘토님~ 피드백 주신 부분 반영해보았습니다~

2024-05-24 05:39 UTC, f-lab-jake requested changes

2024-05-24 05:39 UTC, f-lab-jake commented on level_0/정수를_나선형으로_배치하기.ts
> +        left++;
요걸 for문으로 돌수있지 않을까요?
힌트는 `d = [[0, 1], [1,0], [-1,0], [0,-1]]` 꼴의 배열을 쓰는것입니다.
각각의 배열은 이동하는 방향을 나타냅니다.

2024-05-24 05:39 UTC, f-lab-jake commented on level_0/특별한_이차원_배열1.ts
>      }
`arr`을 변경하지 않고 만들어보세요. lodash의 `range`를 써보세요.

2024-06-10 05:32 UTC, limbs722 commented
@f-lab-jake 멘토님 피드백 부탁드립니다~

2024-06-13 07:27 UTC, merged