20240524 문제풀이
limbs722/ts-snippets pull request #14
Opened 2024-05-24 03:07 UTC by limbs722

@f-lab-jake 멘토님~ 피드백 부탁드립니다~

2024-05-24 05:40 UTC, f-lab-jake requested changes

2024-05-24 05:40 UTC, f-lab-jake commented on level_0/분수의_덧셈.ts
> +    }
arrow function은 return을 뺄수있습니다.

2024-05-24 05:40 UTC, f-lab-jake commented on level_0/분수의_덧셈.ts
> +    }
그리고 이런 함수는 클로저가 아닌 전역으로 선언해도됩니다.

2024-05-31 07:11 UTC, limbs722 commented
@f-lab-jake 멘토님 피드백 주신 부분 수정했습니다~!

2024-06-02 11:09 UTC, f-lab-jake approved these changes

2024-06-03 07:30 UTC, merged