20240530 문제풀이
limbs722/ts-snippets pull request #15
Opened 2024-05-31 07:12 UTC by limbs722

@f-lab-jake 멘토님~ 피드백 부탁드립니다~

2024-06-02 11:12 UTC, f-lab-jake requested changes

2024-06-02 11:12 UTC, f-lab-jake commented on level_0/중앙값_구하기.ts
> +    const median = Math.floor((array.length - 1) / 2);
`Math.floor`를 쓰지 말아보세요

2024-06-02 11:12 UTC, f-lab-jake commented on level_0/최빈값_구하기.ts
> +    }, {});
`acc`를 수정하지마세요. 그걸 못피하겠으면 차라리 for문을 쓰세요.

2024-06-02 11:12 UTC, f-lab-jake commented on level_0/최빈값_구하기.ts
> +    return Number(Object.keys(countObj).find(key => countObj[key] === max));
간결하게 고쳐보세요.

2024-06-02 11:12 UTC, f-lab-jake commented on level_0/피자_나눠_먹기2.ts
> +    }
그냥 `gcd`여도 족합니다. 어차피 거의모든게 cacl 아니던가요?

2024-06-03 09:17 UTC, limbs722 commented
@f-lab-jake 멘토님! 피드백 주신 부분 반영해보았습니다~!

2024-06-03 12:39 UTC, f-lab-jake requested changes

2024-06-03 12:39 UTC, f-lab-jake commented on level_0/최빈값_구하기.ts
> +    return [...countMap].sort(([a_num, a_cnt], [b_num, b_cnt]) => b_cnt - a_cnt)[0][1];
`countMap.values()`를 변수로 빼는게 좋겟죠?

2024-06-11 12:01 UTC, f-lab-jake approved these changes

2024-06-13 07:27 UTC, merged