20240531 문제풀이
limbs722/ts-snippets pull request #16
Opened 2024-05-31 08:18 UTC by limbs722

@f-lab-jake 멘토님~ 피드백 부탁드립니다~!!

2024-06-02 11:13 UTC, f-lab-jake requested changes

2024-06-02 11:13 UTC, f-lab-jake commented on level_0/옷가게_할인_받기.ts
> +    }
개선해봅시다.

2024-06-02 11:13 UTC, f-lab-jake commented on level_0/짝수_홀수_개수.ts
> +    return [num_list.filter(v => v % 2 === 0).length, num_list.filter(v => v % 2 !== 0).length];
효율적으로 개선해보세요.

2024-06-03 09:17 UTC, limbs722 commented
@f-lab-jake 멘토님 피드백 주신 부분 개선 해보았습니다~!

2024-06-03 12:38 UTC, f-lab-jake requested changes

2024-06-03 12:38 UTC, f-lab-jake commented on level_0/옷가게_할인_받기.ts
>      }
아주 훌륭한데 destructuring만좀 까먹지 맙시다.

2024-06-03 12:38 UTC, f-lab-jake commented on level_0/짝수_홀수_개수.ts
> +        }
`++`을 한번만 쓰도록 고쳐보세요.

2024-06-10 05:41 UTC, limbs722 commented
@f-lab-jake 피드백 주신 부분 반영해보았습니다~

2024-06-11 12:02 UTC, f-lab-jake approved these changes

2024-06-11 12:03 UTC, f-lab-jake approved these changes

2024-06-13 07:27 UTC, merged