20240609 문제풀이
limbs722/ts-snippets pull request #17
Opened 2024-06-10 05:42 UTC by limbs722

@f-lab-jake 멘토님~ 피드백 부탁 드립니다~

2024-06-11 12:05 UTC, f-lab-jake requested changes

2024-06-11 12:05 UTC, f-lab-jake commented on level_0/개미_군단.ts
> +    return Math.trunc(hp / 5) + Math.trunc((hp % 5) / 3) + (hp % 5) % 3;
확장성있게 짜보세요

2024-06-11 12:05 UTC, f-lab-jake commented on level_0/구슬을_나누는_경우의_수.ts
> +    if (share === 0 || balls === share) return 1;
빼도되지않나요?

2024-06-11 12:05 UTC, f-lab-jake commented on level_0/양꼬치.ts
> +    }
중복을 제거하세요

2024-06-11 12:05 UTC, f-lab-jake commented on level_0/외계행성의_나이.ts
> +    });
그냥 for문 쓰세요. 무슨 차이일까요?

2024-06-14 09:32 UTC, limbs722 commented
@f-lab-jake 피드백 주신 부분 반영해봤습니다!

2024-06-16 13:12 UTC, f-lab-jake requested changes

2024-06-16 13:12 UTC, f-lab-jake commented on level_0/개미_군단.ts
> +    return general + soldier + worker;
일반화 해서 짜보세요

2024-06-16 13:12 UTC, f-lab-jake commented on level_0/양꼬치.ts
> +    discount = Math.trunc(n / 10) > k ? k * 20000 : Math.trunc(n / 10) * 2000;
여전히 중복이 있습니다.

2024-06-21 11:04 UTC, f-lab-jake requested changes

2024-06-21 11:04 UTC, f-lab-jake commented on level_0/개미_군단.ts
> +        }
중복을 제거하세요. 그리고 여전히 확장성이 없습니다. `hpType`을 수정하면 while문 안의 본문도 고쳐야합니다. 전혀 개선이아닙니다.

2024-06-24 05:41 UTC, f-lab-jake approved these changes
사실 원래 `antTypes` 구조에서도 `Object.entries`, `Object.keys`를 쓰면 가능하긴합니다.

2024-06-24 06:28 UTC, merged