2024/04/15
limbs722/ts-snippets pull request #2
Opened 2024-04-16 07:22 UTC by limbs722

@f-lab-jake 코드리뷰 부탁드립니다!

2024-04-17 00:08 UTC, f-lab-jake requested changes

2024-04-17 00:08 UTC, f-lab-jake commented on level_0/수열과_구간_쿼리4.ts
> +            if (i % v[2] === 0) {
`v`를 destructuring하고 튜플의 경우 인덱싱(`v[i]`같은거)을 피하세요

2024-04-17 00:08 UTC, f-lab-jake commented on level_0/카운트업.ts
> +    return answer;
`answer`같은거 관성적으로 쓸 필요없습니다.

2024-04-17 00:08 UTC, f-lab-jake commented on level_0/카운트업.ts
> +    return answer;
lodash에서 같은 기능을하는 함수를 찾아 써보세요.

2024-04-17 00:08 UTC, f-lab-jake commented on level_0/배열만들기4.ts
> +                i++;
중복을 줄이세요

2024-04-17 00:08 UTC, f-lab-jake commented on level_0/배열만들기4.ts
> +                i++;
`i` 변수없이 해보세요(성능상 더 낫진 않습니다)

2024-04-18 07:53 UTC, limbs722 commented
ㅇ

2024-04-20 13:07 UTC, f-lab-jake requested changes

2024-04-20 13:07 UTC, f-lab-jake commented on level_0/배열만들기4.ts
> +        i--;
더하기를 상쇄하려고 빼는건 이해하기 어렵네요

2024-04-22 10:22 UTC, limbs722 reviewed
@f-lab-jake 멘토님 피드백 반영해보았습니다~

2024-04-22 10:24 UTC, limbs722 commented on level_0/배열만들기4.ts
> +        i--;
흠 다시보니 쓸데없는 부분이었네요...피드백 감사합니다!

2024-04-22 15:52 UTC, f-lab-jake approved these changes

2024-04-23 01:50 UTC, merged