20240710 문제풀이
limbs722/ts-snippets pull request #24
Opened 2024-07-13 05:18 UTC by limbs722

@f-lab-jake 멘토님 피드백 부탁드립니다~

2024-07-14 15:21 UTC, f-lab-jake requested changes

2024-07-14 15:21 UTC, f-lab-jake commented on level_0/다항식_더하기.ts
> +          sumX += Number(n) || 1;
0x일 경우는 어쩌죠?

2024-07-14 15:21 UTC, f-lab-jake commented on level_0/최댓값_만들기.ts
> +  return Math.max(orderd[0] * orderd[1], orderd[len - 1] * orderd[len - 2]);
`at` 쓰세요

2024-07-14 15:21 UTC, f-lab-jake commented on level_0/캐릭터의_죄표.ts
> +  });
`reduce` 써보세요

2024-07-14 15:21 UTC, f-lab-jake commented on level_0/캐릭터의_죄표.ts
> +  };
숨겨진 중복을찾아 제거하세요

2024-07-16 08:03 UTC, limbs722 commented on level_0/다항식_더하기.ts
> +          sumX += Number(n) || 1;
문제에 "polynomial은 양의 정수, 공백, ‘x’, ‘+'로 이루어져 있습니다." 라는 조건이 있어서 '0x'가 주어지는 상황은 고려하지 않았습니다..

2024-07-16 10:11 UTC, f-lab-jake requested changes

2024-07-16 10:11 UTC, f-lab-jake commented on level_0/캐릭터의_죄표.ts
> +      'down': ([posX, posY]: number[]) => ([posX, posY > -y_len ? posY - 1 : posY])
`Math.max`, `Math.min`을 활용하세요

2024-07-22 14:46 UTC, f-lab-jake requested changes

2024-07-22 14:46 UTC, f-lab-jake commented on level_0/캐릭터의_죄표.ts
> +      down: ([posX, posY]) => [posX, posY > -y_len ? posY - 1 : posY],
`Math.max` 쓰는 개선안 기억하시죠?

2024-07-25 06:04 UTC, f-lab-jake approved these changes

2024-07-29 03:22 UTC, merged