20240722 문제풀이
limbs722/ts-snippets pull request #25
Opened 2024-07-24 07:06 UTC by limbs722

@f-lab-jake 멘토님~ 피드백 부탁드립니다~... 좀 더 나이스하게 풀고 싶었는데 어렵네요..

2024-07-25 06:07 UTC, f-lab-jake requested changes

2024-07-25 06:07 UTC, f-lab-jake commented on level_0/숨어있는_숫자의_덧셈2.ts
> +        }
구조를 고쳐서 `sum`을 쓰세요

2024-07-25 06:07 UTC, f-lab-jake commented on level_0/안전지대.ts
반복되는 순회로직을 제네레이터로 고쳐보세요

2024-07-25 06:07 UTC, f-lab-jake commented on level_1/삼총사.ts
> +// https://school.programmers.co.kr/learn/courses/30/lessons/131705?language=javascript
멘토링 시간에 얘기합시다.

2024-08-22 01:34 UTC, f-lab-jake requested changes

2024-08-22 01:34 UTC, f-lab-jake commented on level_1/삼총사.ts
> +    function find(start: number, combination: number[]): number {
인자 `start: number` 대신에 `numbers: number[]`로 바꿔보세요.

2024-09-06 14:41 UTC, f-lab-jake approved these changes

2024-09-06 14:43 UTC, f-lab-jake requested changes

2024-09-06 14:43 UTC, f-lab-jake commented on level_1/삼총사.ts
> +        if (comb.reduce((acc, cur) => acc + cur, 0) === 0) {
`reduce` 사용을 피하세요

2024-09-06 14:43 UTC, f-lab-jake commented on level_1/삼총사.ts
> +            res.push(comb);
`push` 사용하지 하지 말아보세요

2024-10-14 15:39 UTC, f-lab-jake reviewed
의도가 전달되지 않은 거 같습니다.
왜 `push`를 쓰는걸 피하라고 했을까요? 변경의 의도가 이해가 안될때는 역으로 질문을 주세요.

2024-10-21 09:11 UTC, limbs722 commented
> 의도가 전달되지 않은 거 같습니다. 왜 `push`를 쓰는걸 피하라고 했을까요? 변경의 의도가 이해가 안될때는 역으로 질문을 주세요.

@f-lab-jake  안녕하세요 멘토님, 말씀하신대로 제가 이해를 잘못한것 같습니다. push 를 쓰지 말라고 하신부분은 배열이 아닌 다른 방법으로 해결하라는 말씀이실까요??

2024-10-22 05:34 UTC, f-lab-jake commented
네 우리가 지금 제네레이터를 왜 쓰고있는걸까요?

2024-10-31 10:11 UTC, limbs722 commented
> 네 우리가 지금 제네레이터를 왜 쓰고있는걸까요?

push를 사용하게 되면 모든 결과를 한꺼번에 배열에 저장하기 때문에 모든 조합을 동시에 보관하게 되고, 제너레이터를 사용하면 결과를 하나씩 생성해서(yield) 반환하기 때문에 필요한 순간에만 메모리를 사용하게 되어 큰데이터셋을 다룰 때 효율이 더 좋습니다...계속해서 제너레이터에 익숙해지도록 연습해야할 것 같습니다..

2024-11-03 07:43 UTC, f-lab-jake approved these changes

2024-11-04 04:24 UTC, merged