20240816 문제풀이
limbs722/ts-snippets pull request #29
Opened 2024-08-16 12:40 UTC by limbs722

@f-lab-jake 멘토님~ 피드백 부탁드립니다~!

2024-08-17 06:27 UTC, f-lab-jake requested changes

2024-08-17 06:27 UTC, f-lab-jake commented on level_0/다음에_올_숫자.ts
> +    const check = (second - first) === (third - second)
변수명을 개선하세요. 정 이름이 애매하면 그냥 변수로 만드는걸 피할수도 있습니다.

2024-08-17 06:27 UTC, f-lab-jake commented on level_0/문자열_밀기.ts
> +    for (const idx in [...A]) {
`...`안해도 됩니다.

2024-08-17 06:27 UTC, f-lab-jake commented on level_0/문자열_밀기.ts
> +    if (A === B) return 0;
이런 땜빵 코드를 빼는게 좋습니다.

2024-08-22 01:34 UTC, f-lab-jake requested changes

2024-08-22 01:34 UTC, f-lab-jake commented on level_0/문자열_밀기.ts
답이 맞게 나오나요 이게?

2024-08-27 13:37 UTC, limbs722 commented on level_0/문자열_밀기.ts
앗 저 [A] 부분의 중괄호를 안지웠네요...

2024-08-29 04:13 UTC, f-lab-jake approved these changes

2024-08-29 04:14 UTC, f-lab-jake requested changes

2024-08-29 04:14 UTC, f-lab-jake commented on level_0/연속된_수의_합.ts
> +    Array.from({ length: num }, (_, i) => i + (center - side));
이런거 lodsah 쓰세요. 이해하느라 머리아프지않나요?

2024-08-30 02:07 UTC, limbs722 commented on level_0/연속된_수의_합.ts
> +    Array.from({ length: num }, (_, i) => i + (center - side));
넵 lodash 적극적으로 활용하겠습니다...!!

2024-08-30 02:07 UTC, merged