20240418 문제풀이
limbs722/ts-snippets pull request #3
Opened 2024-04-18 10:47 UTC by limbs722

@f-lab-jake 코드리뷰 부탁드립니다!

2024-04-20 03:14 UTC, f-lab-jake requested changes
그동안 본 패턴을 흉내내려고하지말고, 그냥 최선을 다해 자연스럽고 읽기좋도록 짜봅시다.

2024-04-20 03:14 UTC, f-lab-jake commented on level_0/9로_나눈_나머지.ts
> +        acc += Number(value);
`acc`를 변경하는것은 의미가 없습니다. 왜그럴까요?

2024-04-20 03:14 UTC, f-lab-jake commented on level_0/문자열_여러번_뒤집기.ts
> +    return queries.reduce((acc, value) => {
`value`를 디스트럭쳐링 하세요.

2024-04-20 03:14 UTC, f-lab-jake commented on level_0/문자열_여러번_뒤집기.ts
> +    return queries.reduce((acc, value) => {
그냥 for문 쓰는게 어떨까요?

2024-04-20 03:14 UTC, f-lab-jake commented on level_0/주사위_게임3.ts
> +    let answer = 0;
굳이 answer안써도 됩니다.

2024-04-20 03:14 UTC, f-lab-jake commented on level_0/주사위_게임3.ts
> +                answer = (Number(keys[0]) + Number(keys[1])) *
answer에 할당을 여기서 왜하죠?

2024-04-20 03:14 UTC, f-lab-jake commented on level_0/주사위_게임3.ts
> +        [value]: (Number(acc[`${value}`]) || 0) + 1
??를 쓰세요

2024-04-22 10:30 UTC, limbs722 reviewed
@f-lab-jake  피드백 주신 부분 반영했습니다!

2024-04-22 10:31 UTC, limbs722 commented on level_0/주사위_게임3.ts
> +                answer = (Number(keys[0]) + Number(keys[1])) *
바로 값을 return하면 되는 문제였는데 불필요한 코드였네요..

2024-04-22 10:31 UTC, limbs722 commented on level_0/주사위_게임3.ts
> +        [value]: (Number(acc[`${value}`]) || 0) + 1
첫번째 항이 null 이거나 undefined 일 때 '0'이 되어야 하니 ?? 연산자를 사용하는게 더 정확하겠네요!

2024-04-26 06:20 UTC, limbs722 commented
@f-lab-jake 피드백 주신대로 reduce의 acc를 직접 변경하지 않고 풀이 해보았습니다!

2024-04-26 09:38 UTC, f-lab-jake approved these changes

2024-04-28 05:33 UTC, merged