20240906 문제풀이
limbs722/ts-snippets pull request #30
Opened 2024-09-06 06:51 UTC by limbs722

@f-lab-jake 멘토님~! 피드백 부탁드립니다~

2024-09-06 14:51 UTC, f-lab-jake requested changes

2024-09-06 14:51 UTC, f-lab-jake commented on level_1/약수의 합.ts
> +}
이게 답이 제대로 나오는 코드인가요?

2024-09-06 14:51 UTC, f-lab-jake commented on level_1/하샤드_수.ts
> +    return String(n).split('').reduce((acc, value) => acc + Number(value), 0);
안좋은패턴을 찾아서 개선하세요.

2024-09-08 09:47 UTC, limbs722 commented on level_1/약수의 합.ts
> +}
코드 정리하다가 count 변수 증가 시키는걸 없애버렸네요..

2024-09-08 10:12 UTC, limbs722 commented on level_1/하샤드_수.ts
> +    return String(n).split('').reduce((acc, value) => acc + Number(value), 0);
[문자열 -> 배열 -> 배열 안에 있는 인자를 숫자로 변환] 하는 과정 대신 각자리의 숫자를 합하는 while 문을 작성하였습니다.

2024-09-09 01:09 UTC, f-lab-jake requested changes

2024-09-09 01:09 UTC, f-lab-jake commented on level_1/하샤드_수.ts
> +    return sum;
이 해법이 왜 더 낫나요?

2024-09-09 03:05 UTC, limbs722 commented on level_1/하샤드_수.ts
> +    return sum;
인자로 받은 'n'의 타입을 변환하지 않아 더 안전하다고 판단했습니다. 그리고 자릿수의 합을 필요로하는 곳에 언제든 가져다 사용할 수 있습니다.

2024-09-10 01:49 UTC, f-lab-jake commented on level_1/하샤드_수.ts
> +    return sum;
> 인자로 받은 'n'의 타입을 변환하지 않아 더 안전하다고 판단했습니다. 그리고 자릿수의 합을 필요로하는 곳에 언제든 가져다 사용할 수 있습니다.

요건 저도 캐치못했네요. 좋은 지점입니다.
그런데 원래 해법이 더 나은부분도 있습니다. 그게 뭘까요?
원래 의도한 변경은 단지 `reduce`사용을 제거하는것입니다.

2024-09-10 04:06 UTC, limbs722 commented on level_1/하샤드_수.ts
> +    return sum;
reduce 대신 forEach문을 사용한다면 주어진 숫자의 자릿수 만큼만 순회하고 합을 구하기 때문에 안전합니다.

2024-09-12 10:33 UTC, f-lab-jake commented on level_1/하샤드_수.ts
> +    return sum;
좀더 자세히 설명해주세요

2024-09-13 06:05 UTC, limbs722 commented on level_1/하샤드_수.ts
> +    return sum;
음 다시 생각해보니 reduce 를 사용하지 않는다면 lodash의 sum 메소드를 이용해
`const strArr = String(n).split('').map(v => Number(v));`
`return _.sum(strArr);`
위와 같이 작성할 수 있을것 같습니다.
그런데 숫자 배열의 합을 구할 때에도 reduce 를 사용하는 것이 좋은 방법이 아닌건지 궁금합니다..!

2024-09-13 07:56 UTC, f-lab-jake commented on level_1/하샤드_수.ts
> +    return sum;
네 그게 맞습니다. 저게 왜 더 낫나요?

2024-09-13 07:56 UTC, f-lab-jake commented on level_1/하샤드_수.ts
> +    return sum;
그리고 `map(Number)`해도 됩니다

2024-11-07 05:17 UTC, limbs722 commented on level_1/하샤드_수.ts
> +    return sum;
> 네 그게 맞습니다. 저게 왜 더 낫나요?

제 생각으로는 reduce 보다 lodash sum 함수나, forEach를 사용하는것이 더 직관적이고 단순히 '배열 요소들의 합'을 구한다는 목적에 
 더 부합하다고 생각합니다.
 reduce는 누적 처리 연산을 할 때 더 유용할 것 같습니다..!

2024-11-08 15:23 UTC, f-lab-jake commented on level_1/하샤드_수.ts
> +    return sum;
`reduce`는 자유도가 너무높아서 어차피 안의 코드를 다읽어야합니다. 조금만 읽어도 뜻을 파악할수있는 코드를 짜야합니다.
여기서 이제 머지하죠.

2024-11-08 15:24 UTC, f-lab-jake approved these changes

2024-11-12 09:29 UTC, merged