2024/04/19 ~ 2024/04/22 문제풀이
limbs722/ts-snippets pull request #4
Opened 2024-04-22 11:47 UTC by limbs722

@f-lab-jake 코드 리뷰 부탁드립니다!

2024-04-22 15:52 UTC, f-lab-jake requested changes

2024-04-22 15:52 UTC, f-lab-jake commented on level_0/qrcode.ts
> +    }).join('');
배열에 `undefined`를 포함한 채로 `join`하면 빈문자열 취급되는 모양이군요.
별로 안좋은 동작인데 거기에 의존한 풀이입니다.
`map`을 쓰지말아보세요.

2024-04-22 15:52 UTC, f-lab-jake commented on level_0/배열만들기5.ts
> +    }, []);
`filter`를 쓰세요. 그리고 `reduce`에서 `acc`를 변경하는건 잘못된 용법입니다.

2024-04-22 15:52 UTC, f-lab-jake commented on level_0/배열만들기5.ts
> +    }, []);
차라리 for문을 쓰는게 낫습니다.

2024-04-23 01:51 UTC, limbs722 commented on level_0/배열만들기5.ts
> +    }, []);
reduce 메소드에 대해 더 스터디 해보겠습니다!

2024-04-26 06:21 UTC, limbs722 commented
@f-lab-jake 피드백 주신대로 reduce 대신 filter 메소드를 이용해 풀이 해보았습니다~

2024-04-26 09:39 UTC, f-lab-jake requested changes

2024-04-26 09:39 UTC, f-lab-jake commented on level_0/부분_문자열 이어_붙여_문자열_만들기.ts
> +    }).join('');
lodash의 `zip`을 활용해보세요

2024-04-28 10:18 UTC, limbs722 commented
@f-lab-jake  말씀주신대로 join 메소드 활용해서 풀어보았습니다!

2024-04-28 12:36 UTC, f-lab-jake approved these changes

2024-04-29 06:20 UTC, merged