20240426 ~ 20240428 문제풀이
limbs722/ts-snippets pull request #5
Opened 2024-04-28 10:17 UTC by limbs722

@f-lab-jake 멘토님 피드백 부탁드립니다!!

2024-04-28 12:35 UTC, f-lab-jake requested changes

2024-04-28 12:35 UTC, f-lab-jake commented on level_0/가까운_1_찾기.ts
> +    let answer = -1;
`answer`쓰지말아보세요

2024-04-28 12:35 UTC, f-lab-jake commented on level_0/문자_개수_세기.ts
> +    return result;
65, 90, 71 이런 숫자를 magic number라고 합니다.
magic number를 제거하세요.

2024-04-29 08:11 UTC, limbs722 commented
@f-lab-jake 피드백 주신 부분 반영해서 다시 풀이해보았습니다~!

2024-04-30 02:57 UTC, f-lab-jake requested changes

2024-04-30 02:57 UTC, f-lab-jake commented on level_0/문자_개수_세기.ts
>      const result = Array(52).fill(0);
52도 빼봅시다

2024-04-30 07:33 UTC, limbs722 commented
@f-lab-jake 저 부분을 왜 생각 못했을까요...좀 더 꼼꼼하게 풀어야겠습니다..피드백 반영 했습니다!

2024-05-01 01:14 UTC, f-lab-jake approved these changes

2024-05-02 07:12 UTC, merged