20240429 문제풀이
limbs722/ts-snippets pull request #6
Opened 2024-04-29 08:12 UTC by limbs722

@f-lab-jake 멘토님! 피드백 부탁드립니다!!

2024-04-30 02:58 UTC, f-lab-jake requested changes

2024-04-30 02:58 UTC, f-lab-jake commented on level_0/배열_조각하기.ts
> +        }
중복을 줄이세요

2024-04-30 02:58 UTC, f-lab-jake commented on level_0/배열_조각하기.ts
> +    query.map((v, i) => {
리턴값을 사용하지않는 `map`을 쓰지마세요

2024-04-30 02:58 UTC, f-lab-jake commented on level_0/배열만들기3.ts
> +    const [a1, b1] = intervals[0];
https://yamoo9.gitbook.io/typescript/types/tuple
를 배워서 적용해보세요.
그리고 `intervals[0]`처럼 하지말고 destructuring을 사용하세요

2024-04-30 07:31 UTC, limbs722 commented
@f-lab-jake 피드백 주신 부분 반영해서 다시 풀어보았습니다~ typescript의 tuple도 더 공부 해보겠습니다!

2024-05-01 01:14 UTC, f-lab-jake requested changes

2024-05-01 01:14 UTC, f-lab-jake commented on level_0/배열_조각하기.ts
> +        result = i % 2 === 0 ? result.slice(0, v + 1) : result.slice(v);
여전히 중복이 있습니다

2024-05-01 01:14 UTC, f-lab-jake commented on level_0/배열만들기3.ts
>  function makeArray3(arr: number[], intervals: number[][]) {
타입도 고치세요

2024-05-02 07:25 UTC, limbs722 commented
@f-lab-jake  피드백 주신 부분 반영해보았습니다!

2024-05-02 23:35 UTC, f-lab-jake approved these changes

2024-05-03 02:36 UTC, merged