20240430 문제풀이
limbs722/ts-snippets pull request #7
Opened 2024-04-30 07:33 UTC by limbs722

@f-lab-jake 멘토님 피드백 부탁드립니다!

2024-05-01 01:15 UTC, f-lab-jake requested changes

2024-05-01 01:15 UTC, f-lab-jake commented on level_0/왼쪽_오른쪽.ts
> +    }
`str_list.entries()`를 쓰세요

2024-05-02 07:26 UTC, limbs722 commented
@f-lab-jake  Array 의 entries() 메서드 사용해서 다시 풀어보았습니다! 이런 방법도 있었네요

2024-05-02 23:36 UTC, f-lab-jake requested changes

2024-05-02 23:36 UTC, f-lab-jake commented on level_0/왼쪽_오른쪽.ts
> +            return str_list.slice(idx + 1);
3항 연산자를 활용하세요

2024-05-04 03:38 UTC, f-lab-jake approved these changes

2024-05-04 03:38 UTC, f-lab-jake commented on level_0/왼쪽_오른쪽.ts
> +        return str_list.slice(...ele === 'l' ? [0, idx] : [idx + 1]);
음 요건 원래가 더 나은것 같네요. 'l' 비교가 중복되어 있네요.

2024-05-04 03:58 UTC, merged