20240502 문제풀이
limbs722/ts-snippets pull request #8
Opened 2024-05-02 09:50 UTC by limbs722

@f-lab-jake 멘토님 피드백 부탁드립니다~!

2024-05-02 23:38 UTC, f-lab-jake requested changes

2024-05-02 23:38 UTC, f-lab-jake commented on level_0/1로_만들기.ts
> +            count++;
3항 연산자를 활용하세요

2024-05-02 23:38 UTC, f-lab-jake commented on level_0/수열과_구간_쿼리1.ts
> +        const [s, e] = query;
그냥 인자에서 destructruing해도 됩니다

2024-05-02 23:38 UTC, f-lab-jake commented on level_0/조건에_맞게_수열_변환하기_2.ts
> +        }
불필요한 else입니다

2024-05-04 04:00 UTC, limbs722 commented
@f-lab-jake 멘토님~ 피드백 주신 부분 반영하여 다시 풀이 해보았습니다~!

2024-05-04 11:07 UTC, f-lab-jake approved these changes

2024-05-06 03:23 UTC, merged